services:
  - type: web
    name: attendance-management-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: php-fpm
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tramway.proxy.rlwy.net
      - key: DB_PORT
        value: 56073
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: zSVPtwkXahkdbbhKLYQqZpTjbdhMKteL
